version: '3.8'

services:
  # Nome do serviço da sua aplicação
  light-novel-app:
    # A chave "platform" resolve erros de 'exec format error'.
    # Garante que o Docker construa a imagem para a arquitetura correta.
    platform: linux/arm64
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Reinicia o container automaticamente se ele falhar
    restart: unless-stopped
    # Carrega as variáveis de ambiente do seu arquivo .env local
    env_file:
      - ./backend/.env
    # Mapeia a porta 3000 do seu computador para a porta 3000 do container
    ports:
      - "7080:7080"
    # Define um volume para persistir os dados da pasta de uploads
    # Isso garante que as imagens enviadas não sejam perdidas se o container for recriado
    volumes:
      - ./public/uploads:/app/public/uploads